### GET request
GET http://127.0.0.1:8080/users/5558d053-5a63-11f0-8792-00155dd4e74c

### POST request
POST http://127.0.0.1:8080/users
Content-Type: application/json

{
  "name": "Sam",
  "email": "sam@example.com"
}